name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Project
      run: mvn clean install -DskipTests
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t hasnains312/library .
    - name: Push to Dockerhub
      run: docker push hasnains312/library:latest 


  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: sudo docker pull hasnains312/library:latest
      - name: Delete old container
        run: sudo docker rm -f library
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name library hasnains312/library
